use super::inventory::SkillInventoryResult;

/// Render inventory as human-readable text.
pub fn render_inventory_text(result: &SkillInventoryResult) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push("Skill Asset Inventory".to_string());
    lines.push("=====================".to_string());
    lines.push(format!("Schema:  {}", result.schema_version));
    lines.push(format!("Roots:   {}", result.roots_scanned.join(", ")));
    lines.push(String::new());
    lines.push(format!(
        "Summary: total {} (global {}, optional {}, personal {}); with SKILL.md {}, with description {}, public-allowed guess {}, risk-flagged {}",
        result.summary.total,
        result.summary.global,
        result.summary.optional,
        result.summary.personal,
        result.summary.with_skill_md,
        result.summary.with_description,
        result.summary.public_allowed,
        result.summary.flagged_risk,
    ));
    lines.push(String::new());
    for e in &result.entries {
        let md = if e.has_skill_md { "md" } else { "NO-md" };
        let desc = if e.description_present {
            "desc"
        } else {
            "no-desc"
        };
        let public = if e.public_allowed_guess {
            "public?"
        } else {
            "private"
        };
        lines.push(format!(
            "  [{}] {} ({}, {}, {})",
            e.source_category, e.name, md, desc, public
        ));
        if !e.risk_hints.is_empty() {
            lines.push(format!("      risk hints: {}", e.risk_hints.join(", ")));
        }
    }
    lines.join("\n")
}

/// Render inventory as JSON.
pub fn render_inventory_json(result: &SkillInventoryResult) -> String {
    serde_json::to_string_pretty(result)
        .unwrap_or_else(|e| format!(r#"{{"error":"JSON serialization failed: {}"}}"#, e))
}

/// Render inventory as a Markdown report (for governance/skills-inventory.md).
pub fn render_inventory_markdown(result: &SkillInventoryResult) -> String {
    let mut out: Vec<String> = Vec::new();
    out.push("# Skill Asset Inventory".to_string());
    out.push(String::new());
    out.push(format!(
        "_Generated by `ags skill inventory --write`. Schema `{}`. Read-only scan of `SKILL.md` files; no secrets, tokens, or runtime files are read._",
        result.schema_version
    ));
    out.push(String::new());
    out.push("## Summary".to_string());
    out.push(String::new());
    out.push("| Metric | Count |".to_string());
    out.push("|---|---|".to_string());
    out.push(format!("| Total skills | {} |", result.summary.total));
    out.push(format!("| global-skills | {} |", result.summary.global));
    out.push(format!(
        "| skill-packs/optional | {} |",
        result.summary.optional
    ));
    out.push(format!(
        "| skill-packs/personal | {} |",
        result.summary.personal
    ));
    out.push(format!(
        "| With SKILL.md | {} |",
        result.summary.with_skill_md
    ));
    out.push(format!(
        "| With description | {} |",
        result.summary.with_description
    ));
    out.push(format!(
        "| Public-allowed (guess) | {} |",
        result.summary.public_allowed
    ));
    out.push(format!(
        "| Risk-flagged | {} |",
        result.summary.flagged_risk
    ));
    out.push(String::new());
    out.push("## Skills".to_string());
    out.push(String::new());
    out.push(
        "| Category | Name | SKILL.md | Description | Public-allowed (guess) | Risk hints |"
            .to_string(),
    );
    out.push("|---|---|---|---|---|---|".to_string());
    for e in &result.entries {
        let risk = if e.risk_hints.is_empty() {
            "—".to_string()
        } else {
            e.risk_hints.join(", ")
        };
        out.push(format!(
            "| {} | {} | {} | {} | {} | {} |",
            e.source_category,
            e.name,
            if e.has_skill_md { "yes" } else { "no" },
            if e.description_present { "yes" } else { "no" },
            if e.public_allowed_guess { "yes" } else { "no" },
            risk,
        ));
    }
    out.push(String::new());
    out.join("\n")
}
