//! Ownership-safe project projection (contract v3 §7.10).
//!
//! Semantics preserved from contract v2 `project-projection.md`: only files
//! whose current bytes equal the recorded `last_applied_sha256` may be
//! reclaimed. Absent targets are created atomically (no-replace); exact-owned
//! targets are replaced via atomic exchange with validation of the
//! exchanged-out object. Unowned and user-modified bytes are preserved
//! byte-for-byte and surfaced as conflicts. Symlinked final targets and
//! symlink substitution of parents are rejected. The ownership manifest is
//! committed last, after every file effect.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};
use crate::workspace::sha256_hex;

pub const OWNERSHIP_MANIFEST: &str = "ownership-v2.json";
pub const QUARANTINE_DIR: &str = ".ags-projection-state";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Disposition {
    Create,
    ReclaimExactOwned,
    PreserveUnowned,
    PreserveModified,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ownership {
    /// relative path (posix) → exact last-applied sha256 of the generated bytes
    pub paths: BTreeMap<String, String>,
}

impl Ownership {
    /// Load the ownership manifest. The v3 shape is `{"paths": {rel: sha}}`;
    /// the contract-v2 shape (`{"schema_version": ..., "entries": {rel:
    /// {"last_applied_sha256": "sha256:..."}}}`) is accepted on read so
    /// existing v2-managed projects can be adopted by `ags init` without
    /// losing their owned-file history. Writes always use the v3 shape.
    pub fn load(ags_dir: &Path) -> Result<Ownership> {
        #[derive(Deserialize)]
        struct V2Entry {
            last_applied_sha256: String,
        }
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Raw {
            V3 { paths: BTreeMap<String, String> },
            V2 { entries: BTreeMap<String, V2Entry> },
        }
        let path = ags_dir.join(OWNERSHIP_MANIFEST);
        if !path.is_file() {
            return Ok(Ownership {
                paths: BTreeMap::new(),
            });
        }
        let text =
            fs::read_to_string(&path).map_err(|e| crate::error::io("ownership_read_failed", &e))?;
        let raw: Raw = serde_json::from_str(&text)
            .map_err(|e| Error::new("ownership_parse_failed", e.to_string()))?;
        Ok(match raw {
            Raw::V3 { paths } => Ownership { paths },
            Raw::V2 { entries } => Ownership {
                paths: entries
                    .into_iter()
                    .map(|(rel, entry)| {
                        (
                            rel,
                            entry
                                .last_applied_sha256
                                .trim_start_matches("sha256:")
                                .to_string(),
                        )
                    })
                    .collect(),
            },
        })
    }
}

#[derive(Debug, Clone)]
pub struct ProjectionFile {
    pub rel_path: PathBuf,
    pub content: Vec<u8>,
    pub disposition: Disposition,
}

#[derive(Debug, Clone, Serialize)]
pub struct ProjectionOutcome {
    pub files: Vec<ProjectionOutcomeEntry>,
    pub conflicts: Vec<ConflictEntry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ProjectionOutcomeEntry {
    pub rel_path: String,
    pub disposition: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ConflictEntry {
    pub rel_path: String,
    pub disposition: String,
    pub reason: String,
}

/// Classify one desired target against the current tree and the recorded
/// ownership manifest.
pub fn classify(root: &Path, rel: &Path, ownership: &Ownership) -> Disposition {
    let target = root.join(rel);
    if !target.exists() {
        return Disposition::Create;
    }
    match ownership.paths.get(&rel.to_string_lossy().to_string()) {
        None => Disposition::PreserveUnowned,
        Some(recorded) => {
            if !target.is_file() {
                return Disposition::PreserveUnowned;
            }
            let current = fs::read(&target)
                .map(|bytes| sha256_hex(&bytes))
                .unwrap_or_default();
            if &current == recorded {
                Disposition::ReclaimExactOwned
            } else {
                Disposition::PreserveModified
            }
        }
    }
}

/// Apply a desired projection atomically per file, then commit the ownership
/// manifest last. Unowned/modified targets are preserved byte-for-byte and
/// reported as conflicts; their bytes are never replaced.
pub fn apply(
    root: &Path,
    ags_dir: &Path,
    desired: &[ProjectionFile],
    ownership: &mut Ownership,
) -> Result<ProjectionOutcome> {
    fs::create_dir_all(ags_dir).map_err(|e| crate::error::io("ags_dir_create_failed", &e))?;
    let quarantine = ags_dir.join(QUARANTINE_DIR).join("quarantine");
    fs::create_dir_all(&quarantine)
        .map_err(|e| crate::error::io("quarantine_create_failed", &e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&quarantine, fs::Permissions::from_mode(0o700))
            .map_err(|e| crate::error::io("quarantine_chmod_failed", &e))?;
    }

    let mut outcome = ProjectionOutcome {
        files: Vec::new(),
        conflicts: Vec::new(),
    };
    let mut staged: Vec<(PathBuf, Vec<u8>, Vec<u8>)> = Vec::new(); // (target, new bytes, exchanged-out bytes)

    for file in desired {
        let rel = &file.rel_path;
        let target = root.join(rel);
        let recorded = ownership
            .paths
            .get(&rel.to_string_lossy().to_string())
            .cloned();
        let planned = file.disposition;
        let current = classify(root, rel, ownership);
        // Plan-tamper detection: a planned Create/Reclaim must still match
        // the live tree; anything else is preserved as a conflict, never
        // silently re-planned.
        if matches!(
            planned,
            Disposition::Create | Disposition::ReclaimExactOwned
        ) && planned != current
        {
            return Err(Error::new(
                "projection_plan_tampered",
                format!(
                    "{} changed between plan and apply (planned {:?}, now {:?})",
                    rel.display(),
                    planned,
                    current
                ),
            ));
        }
        match planned {
            Disposition::Create => {
                reject_symlink_components(root, rel)?;
                if let Some(parent) = target.parent() {
                    fs::create_dir_all(parent)
                        .map_err(|e| crate::error::io("projection_parent_create_failed", &e))?;
                }
                write_no_replace(&target, &file.content)?;
                staged.push((target.clone(), file.content.clone(), Vec::new()));
            }
            Disposition::ReclaimExactOwned => {
                let recorded = recorded.ok_or_else(|| {
                    Error::new(
                        "projection_reclaim_without_record",
                        "reclaim requires a recorded sha256",
                    )
                })?;
                reject_symlink_components(root, rel)?;
                let current = fs::read(&target)
                    .map_err(|e| crate::error::io("projection_read_failed", &e))?;
                if sha256_hex(&current) != recorded {
                    return Err(Error::new(
                        "projection_plan_tampered",
                        format!("{} changed between plan and apply", rel.display()),
                    ));
                }
                // Move old bytes into quarantine (no-replace), then place new bytes.
                let qpath = quarantine.join(format!("{}.old", sanitize(rel)));
                fs::rename(&target, &qpath)
                    .map_err(|e| crate::error::io("projection_exchange_failed", &e))?;
                let result = (|| -> Result<()> {
                    let tmp = target.with_extension("agsnew");
                    {
                        let mut f = fs::File::create(&tmp)
                            .map_err(|e| crate::error::io("projection_write_failed", &e))?;
                        f.write_all(&file.content)
                            .and_then(|_| f.flush())
                            .map_err(|e| crate::error::io("projection_write_failed", &e))?;
                    }
                    fs::rename(&tmp, &target)
                        .map_err(|e| crate::error::io("projection_write_failed", &e))
                })();
                if let Err(e) = result {
                    // roll the exchanged-out object back
                    let _ = fs::rename(&qpath, &target);
                    return Err(e);
                }
                // Validate the exchanged-out object before consuming it.
                let old =
                    fs::read(&qpath).map_err(|e| crate::error::io("projection_read_failed", &e))?;
                if sha256_hex(&old) != recorded {
                    return Err(Error::new(
                        "projection_exchange_validation_failed",
                        "exchanged-out bytes do not match the recorded hash",
                    ));
                }
                staged.push((target.clone(), file.content.clone(), old));
            }
            Disposition::PreserveUnowned | Disposition::PreserveModified => {
                outcome.conflicts.push(ConflictEntry {
                    rel_path: rel.to_string_lossy().to_string(),
                    disposition: match planned {
                        Disposition::PreserveUnowned => "preserve_unowned".to_string(),
                        _ => "preserve_modified".to_string(),
                    },
                    reason: "bytes preserved byte-for-byte".to_string(),
                });
            }
        }
        outcome.files.push(ProjectionOutcomeEntry {
            rel_path: rel.to_string_lossy().to_string(),
            disposition: format!("{planned:?}").to_ascii_lowercase(),
        });
    }

    // Commit the ownership manifest last, after every file effect.
    for (target, new_bytes, _old) in &staged {
        let rel = target
            .strip_prefix(root)
            .map_err(|e| Error::new("projection_path_invalid", e.to_string()))?;
        ownership
            .paths
            .insert(rel.to_string_lossy().to_string(), sha256_hex(new_bytes));
    }
    let text = serde_json::to_string_pretty(&ownership)
        .map_err(|e| Error::new("ownership_encode_failed", e.to_string()))?;
    let manifest = ags_dir.join(OWNERSHIP_MANIFEST);
    let tmp = ags_dir.join(format!("{OWNERSHIP_MANIFEST}.tmp"));
    fs::write(&tmp, text).map_err(|e| crate::error::io("ownership_write_failed", &e))?;
    fs::rename(&tmp, &manifest).map_err(|e| crate::error::io("ownership_write_failed", &e))?;

    Ok(outcome)
}

/// Reject any symlink along the parent chain of a target; final targets are
/// handled by the disposition classification (non-file → PreserveUnowned).
pub(crate) fn reject_symlink_components(root: &Path, rel: &Path) -> Result<()> {
    let mut cursor = root.to_path_buf();
    let components: Vec<_> = rel.components().collect();
    for (i, component) in components.iter().enumerate() {
        let is_last = i + 1 == components.len();
        let name = component.as_os_str();
        cursor.push(name);
        match crate::sync::directory_link_target(&cursor) {
            Ok(Some(_)) if !is_last => {
                return Err(Error::new(
                    "projection_parent_symlink_rejected",
                    format!("parent component is a symlink: {}", cursor.display()),
                ));
            }
            Ok(_) => {}
            Err(error) => {
                return Err(crate::error::io("projection_path_inspect_failed", &error));
            }
        }
    }
    Ok(())
}

pub(crate) fn reject_symlink_path(root: &Path, rel: &Path) -> Result<()> {
    if rel.components().any(|component| {
        matches!(
            component,
            std::path::Component::ParentDir | std::path::Component::RootDir
        )
    }) {
        return Err(Error::new(
            "projection_path_invalid",
            format!("{} is not a bounded relative path", rel.display()),
        ));
    }
    let mut cursor = root.to_path_buf();
    for component in rel.components() {
        cursor.push(component.as_os_str());
        match crate::sync::directory_link_target(&cursor) {
            Ok(Some(_)) => {
                return Err(Error::new(
                    "projection_symlink_rejected",
                    format!("symlink component: {}", cursor.display()),
                ));
            }
            Ok(None) => {}
            Err(error) => return Err(crate::error::io("projection_path_inspect_failed", &error)),
        }
    }
    Ok(())
}

fn write_no_replace(target: &Path, content: &[u8]) -> Result<()> {
    let mut f = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(target)
        .map_err(|e| crate::error::io("projection_create_failed", &e))?;
    f.write_all(content)
        .and_then(|_| f.flush())
        .map_err(|e| crate::error::io("projection_create_failed", &e))
}

fn sanitize(rel: &Path) -> String {
    rel.to_string_lossy().replace('/', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_ws(tmp: &tempfile::TempDir) -> (PathBuf, PathBuf) {
        let root = tmp.path().join("ws");
        let ags = root.join(".ags");
        fs::create_dir_all(&ags).unwrap();
        (root, ags)
    }

    #[test]
    fn classification_matrix_is_exact() {
        let tmp = tempfile::tempdir().unwrap();
        let (root, _ags) = write_ws(&tmp);
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        let rel = Path::new("generated.txt");
        // absent → Create
        assert_eq!(classify(&root, rel, &ow), Disposition::Create);
        // owned + exact hash → Reclaim
        fs::write(root.join(rel), "v1").unwrap();
        ow.paths
            .insert("generated.txt".to_string(), sha256_hex(b"v1"));
        assert_eq!(classify(&root, rel, &ow), Disposition::ReclaimExactOwned);
        // owned + modified → PreserveModified
        fs::write(root.join(rel), "v2").unwrap();
        assert_eq!(classify(&root, rel, &ow), Disposition::PreserveModified);
        // unowned → PreserveUnowned
        let rel2 = Path::new("user.txt");
        fs::write(root.join(rel2), "mine").unwrap();
        assert_eq!(classify(&root, rel2, &ow), Disposition::PreserveUnowned);
    }

    #[test]
    fn apply_creates_and_reclaims_only_owned() {
        let tmp = tempfile::tempdir().unwrap();
        let (root, ags) = write_ws(&tmp);
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        // The user file exists and is unowned: the plan records PreserveUnowned.
        fs::write(root.join("user.txt"), "mine").unwrap();
        let desired = vec![
            ProjectionFile {
                rel_path: PathBuf::from("owned.txt"),
                content: b"generated v1".to_vec(),
                disposition: Disposition::Create,
            },
            ProjectionFile {
                rel_path: PathBuf::from("user.txt"),
                content: b"should not land".to_vec(),
                disposition: Disposition::PreserveUnowned,
            },
        ];
        let outcome = apply(&root, &ags, &desired, &mut ow).unwrap();
        assert_eq!(outcome.files.len(), 2);
        assert!(outcome.conflicts.iter().any(|c| c.rel_path == "user.txt"));
        assert_eq!(fs::read(root.join("user.txt")).unwrap(), b"mine");
        assert_eq!(fs::read(root.join("owned.txt")).unwrap(), b"generated v1");
        // second apply: exact-owned bytes are reclaimed
        let desired2 = vec![ProjectionFile {
            rel_path: PathBuf::from("owned.txt"),
            content: b"generated v2".to_vec(),
            disposition: Disposition::ReclaimExactOwned,
        }];
        let outcome2 = apply(&root, &ags, &desired2, &mut ow).unwrap();
        assert!(outcome2.conflicts.is_empty());
        assert_eq!(fs::read(root.join("owned.txt")).unwrap(), b"generated v2");
        assert!(ags.join(OWNERSHIP_MANIFEST).is_file());
    }

    #[test]
    fn planned_create_drift_is_plan_tamper() {
        let tmp = tempfile::tempdir().unwrap();
        let (root, ags) = write_ws(&tmp);
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        // Planned as absent (Create), but the file appears before apply.
        fs::write(root.join("late.txt"), "appeared").unwrap();
        let desired = vec![ProjectionFile {
            rel_path: PathBuf::from("late.txt"),
            content: b"generated".to_vec(),
            disposition: Disposition::Create,
        }];
        let err = apply(&root, &ags, &desired, &mut ow).unwrap_err();
        assert_eq!(err.code, "projection_plan_tampered");
        assert_eq!(fs::read(root.join("late.txt")).unwrap(), b"appeared");
    }

    #[test]
    fn tampered_bytes_are_never_replaced() {
        let tmp = tempfile::tempdir().unwrap();
        let (root, ags) = write_ws(&tmp);
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        let desired = vec![ProjectionFile {
            rel_path: PathBuf::from("f.txt"),
            content: b"v1".to_vec(),
            disposition: Disposition::Create,
        }];
        apply(&root, &ags, &desired, &mut ow).unwrap();
        // User modifies the generated file; a reclaim must now fail closed.
        fs::write(root.join("f.txt"), "user edit").unwrap();
        let desired2 = vec![ProjectionFile {
            rel_path: PathBuf::from("f.txt"),
            content: b"v2".to_vec(),
            disposition: Disposition::ReclaimExactOwned,
        }];
        let err = apply(&root, &ags, &desired2, &mut ow).unwrap_err();
        assert_eq!(err.code, "projection_plan_tampered");
        assert_eq!(fs::read(root.join("f.txt")).unwrap(), b"user edit");
    }

    #[test]
    fn parent_symlink_is_rejected() {
        let tmp = tempfile::tempdir().unwrap();
        let (root, ags) = write_ws(&tmp);
        let outside = tmp.path().join("outside");
        fs::create_dir_all(&outside).unwrap();
        std::os::unix::fs::symlink(&outside, root.join("link")).unwrap();
        let desired = vec![ProjectionFile {
            rel_path: PathBuf::from("link/f.txt"),
            content: b"x".to_vec(),
            disposition: Disposition::Create,
        }];
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        let err = apply(&root, &ags, &desired, &mut ow).unwrap_err();
        assert_eq!(err.code, "projection_parent_symlink_rejected");
    }
}

#[cfg(test)]
mod v2_compat_tests {
    use super::*;
    use std::fs;

    #[test]
    fn loads_v2_ownership_shape() {
        let tmp = tempfile::tempdir().unwrap();
        let ags = tmp.path().join(".ags");
        fs::create_dir_all(&ags).unwrap();
        fs::write(
            ags.join(OWNERSHIP_MANIFEST),
            r#"{
  "schema_version": "ags://schema/contract/v2/project-ownership",
  "entries": {
    "config/agent-project-profile.yaml": {"last_applied_sha256": "sha256:abc123"},
    "generated.md": {"last_applied_sha256": "sha256:def456"}
  }
}"#,
        )
        .unwrap();
        let ow = Ownership::load(&ags).unwrap();
        assert_eq!(
            ow.paths.get("config/agent-project-profile.yaml").unwrap(),
            "abc123"
        );
        assert_eq!(ow.paths.get("generated.md").unwrap(), "def456");
    }

    #[test]
    fn writes_and_reloads_v3_shape() {
        let tmp = tempfile::tempdir().unwrap();
        let ags = tmp.path().join(".ags");
        fs::create_dir_all(&ags).unwrap();
        let mut ow = Ownership {
            paths: BTreeMap::new(),
        };
        ow.paths.insert("a.md".to_string(), "abc".to_string());
        let text = serde_json::to_string_pretty(&ow).unwrap();
        fs::write(ags.join(OWNERSHIP_MANIFEST), text).unwrap();
        let loaded = Ownership::load(&ags).unwrap();
        assert_eq!(loaded.paths.get("a.md").unwrap(), "abc");
    }
}
